name: Run Tests

on:
  pull_request:
    types: labeled

jobs:
  setup-build-deploy:
    name: Setup, Build, and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Run Tests
        run: npm test -- --ci --coverage --reporters=default --reporters=jest-junit
        env:
          CI: true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: jest-test-results
          path: junit.xml
      
      - name: Upload test coverage
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage