name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main
      - expo

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy to Google Cloud Run
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_TEST_SA_KEY }}'
    - name: Set up Google Cloud Platform
      uses: google-github-actions/setup-gcloud@v2
    - name: 'Use gcloud CLI'
      run: 'gcloud info'
    - name: Build and Push Docker image
      run: gcloud builds submit --tag gcr.io/locards-bonny-test/bonny-backend

    - name: Deploy to Cloud Run (Main)
      if: github.ref == 'refs/heads/main'
      run: gcloud run deploy --service-account='bonny-test-backend@locards-bonny-test.iam.gserviceaccount.com' --env-vars-file=.env.yaml --image='gcr.io/locards-bonny-test/bonny-backend' --region='europe-west3' bonny-backend

    - name: Deploy to Cloud Run (Expo)
      if: github.ref == 'refs/heads/expo'
      run: gcloud run deploy --service-account='bonny-test-backend@locards-bonny-test.iam.gserviceaccount.com' --env-vars-file=.env.dev.yaml --image='gcr.io/locards-bonny-test/bonny-backend' --region='europe-west3' bonny-backend-dev
