[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
bonny_program_library = "7yAp4Mpxb11aaDPpRxJhxDnDJY525qTSQNSwQjfhNdnh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/sleyn/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
